name: iOS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
      env:
        FLUTTER_ROOT: ${{ github.workspace }}
        
    - name: Setup iOS certificates
      uses: apple-actions/import-codesigning-certs@v1
      with:
        p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
        p12-password: ${{ secrets.IOS_P12_PASSWORD }}
        
    - name: Setup provisioning profile
      uses: apple-actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.vehicleinspectionapp'
        profile-type: 'IOS_APP_DEVELOPMENT'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
        
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace VehicleInspectionApp.xcworkspace \
                   -scheme VehicleInspectionApp \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath VehicleInspectionApp.xcarchive \
                   archive
                   
    - name: Create IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath VehicleInspectionApp.xcarchive \
                   -exportPath ./build \
                   -exportOptionsPlist exportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: VehicleInspectionApp-iOS
        path: ios/build/VehicleInspectionApp.ipa
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: ios/build/VehicleInspectionApp.ipa
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          iOS build for Vehicle Inspection App
          
          - Build number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 