# Workflow temporalmente deshabilitado por problemas de facturación
# Para habilitar: cambiar 'on' por 'on:' y descomentar las líneas
name: iOS Build and TestFlight

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14  # Usar versión específica en lugar de latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..
        
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace VehicleInspectionApp.xcworkspace \
                   -scheme VehicleInspectionApp \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath build/VehicleInspectionApp.xcarchive \
                   clean archive
                   
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath build/VehicleInspectionApp.xcarchive \
                   -exportPath build/ \
                   -exportOptionsPlist exportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: VehicleInspectionApp-ipa
        path: ios/build/VehicleInspectionApp.ipa
        
    - name: Upload to TestFlight (Optional)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Para subir a TestFlight, necesitas:"
        echo "1. Configurar APP_STORE_CONNECT_API_KEY en los secrets del repositorio"
        echo "2. Configurar APP_STORE_CONNECT_ISSUER_ID en los secrets del repositorio"
        echo "3. Configurar APP_STORE_CONNECT_KEY_ID en los secrets del repositorio"
        echo ""
        echo "O subir manualmente el IPA desde Xcode Organizer"
        
    # Comentario: Para habilitar la subida automática a TestFlight, descomenta las siguientes líneas
    # y configura los secrets en tu repositorio de GitHub
    
    # - name: Upload to TestFlight
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   uses: apple-actions/upload-testflight@v1
    #   with:
    #     app-path: ios/build/VehicleInspectionApp.ipa
    #     api-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
    #     api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
    #     api-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }} 